<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_owy_options',
	'title' => 'Owy Options',
	'fields' => array(
		array(
			'key' => 'field_60701ba047427',
			'label' => 'P2P',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'user_roles' => array(
				0 => 'all',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6050ac4d33beb',
			'label' => 'Custom Peer Server',
			'name' => 'peer_server',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_60749303dc157',
			'label' => '',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'user_roles' => array(
				0 => 'all',
			),
			'message' => '<a target="_blank" href="https://github.com/peers/peerjs-server">Create your peer server</a>',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_60748b6d6d6ea',
			'label' => 'Developer',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'user_roles' => array(
				0 => 'all',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6074906c9f4bb',
			'label' => '',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'user_roles' => array(
				0 => 'all',
			),
			'message' => 'Only available for "Super Admin"',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_60748b886d6eb',
			'label' => 'Vuejs Template development',
			'name' => 'is_template_development',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'user_roles' => array(
				0 => 'super_admin',
			),
			'message' => 'Active',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_60748dcb9ea02',
			'label' => '',
			'name' => 'template_development_server',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'user_roles' => array(
				0 => 'super_admin',
			),
			'default_value' => '',
			'placeholder' => 'Server: http://localhost:8080/ (default if empty)',
		),
		array(
			'key' => 'field_60748bcc6d6ec',
			'label' => 'Vuejs Builder development',
			'name' => 'is_builder_development',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'user_roles' => array(
				0 => 'super_admin',
			),
			'message' => 'Active',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_60748df09ea03',
			'label' => 'Server',
			'name' => 'builder_development_server',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'user_roles' => array(
				0 => 'super_admin',
			),
			'default_value' => '',
			'placeholder' => 'Server: http://localhost:8081/ (default if empty)',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'owy-no-location',
				'operator' => '==',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1618252918,
));

endif;