<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_owy_wp_query_generator',
	'title' => 'Query Generator',
	'fields' => array(
		array(
			'key' => 'field_604cb706d26bf',
			'label' => 'Query name',
			'name' => 'query_name',
			'type' => 'text',
			'instructions' => 'Give a name to your query. You can re-use it in different templates.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_604b75ce25f4a',
			'label' => 'Query Object',
			'name' => 'query_object',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'post' => 'Post types',
				'taxonomy' => 'Taxonomies',
				'term' => 'Terms',
				'user' => 'Users',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_604b75a825f49',
			'label' => 'Post types',
			'name' => 'post_types',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_604b75ce25f4a',
						'operator' => '==',
						'value' => 'post',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_604dd87df4d17',
					'label' => '',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Get post or custom posts',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
				array(
					'key' => 'field_604dd896f4d18',
					'label' => 'Authors in',
					'name' => 'authors_in',
					'type' => 'user',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'role' => '',
					'allow_null' => 1,
					'multiple' => 1,
					'return_format' => 'array',
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
				),
				array(
					'key' => 'field_604dd8d5f4d19',
					'label' => 'Authors not in',
					'name' => 'authors_not_in',
					'type' => 'user',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'role' => '',
					'allow_null' => 1,
					'multiple' => 1,
					'return_format' => 'array',
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
				),
				array(
					'key' => 'field_604dd901f4d1a',
					'label' => 'Taxonomies',
					'name' => 'taxonomies',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_repeater_stylised_button' => 1,
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => '',
					'sub_fields' => array(
						array(
							'key' => 'field_604dd915f4d1b',
							'label' => 'Taxonomy',
							'name' => 'taxonomy',
							'type' => 'acfe_taxonomies',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => '',
							'field_type' => 'checkbox',
							'default_value' => '',
							'return_format' => 'name',
							'layout' => 'vertical',
							'toggle' => 0,
							'allow_custom' => 0,
							'multiple' => 0,
							'allow_null' => 0,
							'choices' => array(
							),
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'search_placeholder' => '',
						),
					),
				),
			),
		),
		array(
			'key' => 'field_604b77f825f4b',
			'label' => 'Taxonomies',
			'name' => 'taxonomies',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_604b75ce25f4a',
						'operator' => '==',
						'value' => 'taxonomy',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
			),
		),
		array(
			'key' => 'field_604b781825f4c',
			'label' => 'Terms',
			'name' => 'terms',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_604b75ce25f4a',
						'operator' => '==',
						'value' => 'term',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
			),
		),
		array(
			'key' => 'field_604b782425f4d',
			'label' => 'Users',
			'name' => 'users',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_604b75ce25f4a',
						'operator' => '==',
						'value' => 'user',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'owy_query',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1615716278,
));

endif;